name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Checkout
        if: success()
        uses: actions/checkout@v1

      - name: Lint with isort
        if: success()
        run: |
          pip install .[all]
          pip install pytest
          pip install isort
          isort -rc --check .
      - name: Lint with flake8
        if: success()
        run: |
          pip install --upgrade pip
          pip install flake8
          flake8 .
      - name: Lint with black
        if: success()
        run: |
          pip install black
          black --check .
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Checkout
        if: success()
        uses: actions/checkout@v1
        with:
          lfs: true

      - name: Install dependencies
        if: success()
        run: |
          sudo apt-get install -y python3-h5py python3-netcdf4 python3-lxml
      - name: Install package
        if: success()
        run: |
          pip install --upgrade pip
          pip install .[all]
      - name: Test with pytest
        if: success()
        run: |
          pip install pytest pytest-cov
          pytest --cov meshio
